{% set name = "tf2onnx" %}
{% set version = "1.8.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/onnx/tensorflow-onnx/archive/v{{ version }}.tar.gz
  sha256: cfea74d85bcf5e5e925548901c948df3abaae9484e2998a2398bdc6d4bc9ae8a

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - pytest-runner
    - numpy
    - onnx >=1.4.1
    - requests
    - six
  run:
    - python
    - onnx >=1.4.1
    - {{ pin_compatible('numpy') }}
    - six
    - requests
    - python-flatbuffers
    - tensorflow >=1.5

test:
  requires:
    - pip
  commands:
    - pip check
    - python -m tf2onnx.convert --help

about:
  home: https://github.com/onnx/tensorflow-onnx
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Tensorflow to ONNX converter
  description: tf2onnx - convert TensorFlow models to ONNX models.
  doc_url: http://simplejson.readthedocs.io/
  dev_url: https://github.com/onnx/tensorflow-onnx

extra:
  recipe-maintainers:
    - marcelotrevisani
    - xhochy
