travis:
  secure:
    BINSTAR_TOKEN: FlnOirM65/2sj9VxvLI1ud9SUc0LtZl8pPf5PbBB6ZwWtfL1HW9Hj7c/fnPTDrpbu+ewe3KdghtiWD/MxhgAPv4/dV2JNYgWkI2HCarckyMBrEJtN0gYWLFfV+PbtISivmBaPwI8cRvyh4tlaFVSHaWEPN6jgsrzpkCF01pJYs3i+KxVupIiKO28EPDiPChYF8+iiUoGYVPQINf05el3IKvUpsfRWkAPgXsgs03k7ZQp5CRBOIyDMsi9PGjppN2Y+U5IJqeIrT7AcTwLBJXZ60DYrx9gREo8+qaFgV4/EgP3MupMZE8MCSktVuWVBlyJaqS5zVAI4p9v+NdAktQLkqgMmEom4ro46Adqy2ZBt0dC1p3qWvCz385E9dJbYhQGn+NwZvOYLnqJLVxtFfLx4WuNJ30RurBYVCMVGvnVvZCEGJYmxbeHW+zOFyFhPz2TxVy6746vs4S0qyW/+GCW48HTsKvvTGZyKi0wZcSePOzEfz1rRRm6WAilPfkjTI0hKgC70lHjWrhEwkGuT/QlZrGAZILWtCxrzAF8XBtCuM6dRU4s5HwVV1T5mreYRZPyjlBYrDxPRAPr+iAWd64f/M0yR+h2mwdj19kbFAiJcWc6gFN6HJI36ATu0+5oDmUY4hk/GUGmLrH4YDj0WuXfcnfyKZvmokQLnaPnNAcl1EY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
